version: '3.9'

services:
  app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
    ports:
      - 8001:80
  
  auth:
    ports:
       - 8002:5142

  proxy:
    volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
       - 5142:5142
