version: '3.9'

networks:
    product-net:
        driver: bridge

services:
  app:
    container_name: main_app
    image: borntowhine/products_catalog
    build:
      context: .
      dockerfile: ProductsCatalog.Frontend/Dockerfile
    networks:
      - product-net
    depends_on:
      - db
      - auth
  
  auth:
    container_name: auth
    hostname: auth
    image: borntowhine/auth
    build:
      context: D:\C#\Practice\ECommerce
      dockerfile: .\Ordering.API\Dockerfile
    networks:
      - product-net
    depends_on:
      - db

  proxy:
    container_name: proxy
    image: nginx:mainline
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - product-net
    depends_on:
      - auth

  db:
    container_name: db
    image: postgres:16.0-alpine3.18
    volumes:
      - products-data:/var/lib/postgresql/data
    networks:
      - product-net

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    networks:
      - product-net
    depends_on:
      - db

volumes:
    products-data:
      